services:
  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./web/client:/web/client
    restart: always

networks:
  my_network:
    driver: bridge